version: '3.9'

services:
  cs-postgresql:
    container_name: cs-postgresql
    image: postgres:13
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    networks:
      - cs-network

  pgadmin:
    container_name: cs-pgadmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - cs-network
      
networks:
  cs-network:
    external: true


